### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by bxrhhy** [dreamsoftin/facebook_audience_network#127]
Machine: Mac os 11.1(big sur)
cpu: intel
iosDevice: iphone 6s(ios14.8.1)
Undefined symbols for architecture arm64:
      "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
          __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork)
      "_OBJC_CLASS_$_SKAdImpression", referenced from:
          objc-class-ref in FBAudienceNetwork(FBAdSKAdNetworkManager.m.o)
      "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
          __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork)
    ld: symbol(s) not found for architecture arm64

**Comment by youssefali424** [comment]
quick solution , specify a working version of FBAudienceNetwork in podfile ex (6.5.1 currently working)
